language: python
python:
  - "3.7"
  - "3.8"
git:
  depth: 3
install:
  - pip install -r requirements.txt
script:
  - python -m unittest discover -s tests
deploy:
  provider: heroku
  skip_cleanup: true
  keep_history: true
  api_key: $HEROKU_API_KEY
  app: mutants-dna-api
  on:
    repo: aviloncho/mutants